# Generated by Django 3.2.13 on 2022-05-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('idEtablissement', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('idMessage', models.AutoField(primary_key=True, serialize=False)),
                ('texteMessage', models.TextField(max_length=6700)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('idNiveau', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStatut', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('idVille', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('idPersonne', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=8, null=True)),
                ('indicatifTel', models.CharField(default='+228', max_length=4, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('idStatut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.statut')),
                ('idVille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.ville')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageEnvoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statutEnvoi', models.CharField(choices=[('À envoyer', 'À envoyer'), ('Envoyé', 'Envoyé'), ('Reçu', 'Reçu'), ('Lu', 'Lu')], default='À envoyer', max_length=50)),
                ('texteMessage', models.TextField(max_length=6700)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('idPersonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('idEnvoi', models.AutoField(primary_key=True, serialize=False)),
                ('statutEnvoi', models.CharField(choices=[('À envoyer', 'À envoyer'), ('Envoyé', 'Envoyé'), ('Reçu', 'Reçu'), ('Lu', 'Lu')], default='À envoyer', max_length=50)),
                ('idEtablissement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.etablissement')),
                ('idMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.message')),
                ('idNiveau', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.niveau')),
                ('idVille', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='contacts.personne')),
                ('idEleve', models.AutoField(primary_key=True, serialize=False)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('idEtablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.etablissement')),
                ('idNiveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.niveau')),
            ],
            bases=('contacts.personne',),
        ),
    ]
