# Generated by Django 3.2.13 on 2022-05-17 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20220517_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='idEleve',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eleve',
            name='personne_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='contacts.personne'),
        ),
    ]
