# Generated by Django 3.2.13 on 2022-05-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20220517_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envoi',
            name='statutEnvoi',
            field=models.CharField(choices=[('A envoyer', 'A envoyer'), ('Envoyé', 'Envoyé'), ('Reçu', 'Reçu'), ('Lu', 'Lu')], default='A envoyer', max_length=50),
        ),
        migrations.AlterField(
            model_name='messageenvoi',
            name='statutEnvoi',
            field=models.CharField(choices=[('A envoyer', 'A envoyer'), ('Envoyé', 'Envoyé'), ('Reçu', 'Reçu'), ('Lu', 'Lu')], default='A envoyer', max_length=50),
        ),
    ]
