# Generated by Django 3.2.11 on 2022-05-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20220517_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageenvoi',
            name='indicatif',
            field=models.CharField(default='+228', max_length=4, null=True),
        ),
    ]
